import { Style } from "util";
import styles from "./animated.module.css";

const LogoAnimated = () => {
  return (
    <>
      <svg
        width="350"
        height="250"
        viewBox="0 0 350 250"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M65.1103 53.302H51.4706C23.0442 53.302 0 76.3462 0 104.773V198.449C0 226.875 23.0442 249.92 51.4706 249.92H247.059C275.485 249.92 298.529 226.875 298.529 198.449V106.661C298.586 103.927 298.586 100.819 298.586 97.3089V25.766C298.586 10.4094 298.586 2.73115 293.813 0.51959C289.04 -1.69195 283.182 3.27225 271.467 13.2007L229.258 48.9722C227.315 50.6194 225.645 52.0341 224.251 53.302H139.446C138.052 52.0345 136.383 50.6204 134.44 48.9739L134.439 48.9724L92.2297 13.2009C80.5144 3.27231 74.6567 -1.69197 69.8835 0.519589C65.1103 2.73115 65.1103 10.4094 65.1103 25.766V53.302Z"
          fill="#FF7E36"
          className="svg-elem-1"
        ></path>
        <path
          d="M214.919 134.041C214.919 161.816 192.263 184.405 164.224 184.405C136.186 184.405 113.53 161.816 113.53 134.041C113.53 106.266 136.186 83.6765 164.224 83.6765C192.263 83.6765 214.919 106.266 214.919 134.041Z"
          fill="white"
          stroke="white"
          stroke-width="15"
          className="svg-elem-2"
        ></path>
        <path
          d="M342.5 134.041C342.5 161.816 319.843 184.405 291.805 184.405C263.767 184.405 241.11 161.816 241.11 134.041C241.11 106.266 263.767 83.6765 291.805 83.6765C319.843 83.6765 342.5 106.266 342.5 134.041Z"
          fill="white"
          stroke="white"
          stroke-width="15"
          className="svg-elem-3"
        ></path>
        <path
          d="M219.265 134.059L224.191 132.964C227.049 132.329 230.011 132.329 232.868 132.964L237.794 134.059"
          stroke="white"
          stroke-width="15"
          className="svg-elem-4"
        ></path>
        <rect
          x="134"
          y="100"
          width="44"
          height="68"
          rx="22"
          fill="#FF7E36"
          className="svg-elem-5"
        ></rect>
        <rect
          x="255"
          y="100"
          width="44"
          height="68"
          rx="22"
          fill="#FF7E36"
          className="svg-elem-6"
        ></rect>
      </svg>
      <style jsx>
        {`
          /***************************************************
             * Generated by SVG Artista on 6/10/2023, 12:05:17 PM
             * MIT license (https://opensource.org/licenses/MIT)
             * W. https://svgartista.net
             **************************************************/

          @-webkit-keyframes animate-svg-stroke-1 {
            0% {
              stroke-dashoffset: 1063.2886962890625px;
              stroke-dasharray: 1063.2886962890625px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 1063.2886962890625px;
            }
          }

          @keyframes animate-svg-stroke-1 {
            0% {
              stroke-dashoffset: 1063.2886962890625px;
              stroke-dasharray: 1063.2886962890625px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 1063.2886962890625px;
            }
          }

          @-webkit-keyframes animate-svg-fill-1 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 126, 54);
            }
          }

          @keyframes animate-svg-fill-1 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 126, 54);
            }
          }

          .svg-elem-1 {
            -webkit-animation: animate-svg-stroke-1 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
              animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s
                both;
            animation: animate-svg-stroke-1 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
              animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s
                both;
          }

          @-webkit-keyframes animate-svg-stroke-2 {
            0% {
              stroke-dashoffset: 319.53125px;
              stroke-dasharray: 319.53125px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 319.53125px;
            }
          }

          @keyframes animate-svg-stroke-2 {
            0% {
              stroke-dashoffset: 319.53125px;
              stroke-dasharray: 319.53125px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 319.53125px;
            }
          }

          @-webkit-keyframes animate-svg-fill-2 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 255, 255);
            }
          }

          @keyframes animate-svg-fill-2 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 255, 255);
            }
          }

          .svg-elem-2 {
            -webkit-animation: animate-svg-stroke-2 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
              animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s
                both;
            animation: animate-svg-stroke-2 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
              animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s
                both;
          }

          @-webkit-keyframes animate-svg-stroke-3 {
            0% {
              stroke-dashoffset: 319.5322265625px;
              stroke-dasharray: 319.5322265625px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 319.5322265625px;
            }
          }

          @keyframes animate-svg-stroke-3 {
            0% {
              stroke-dashoffset: 319.5322265625px;
              stroke-dasharray: 319.5322265625px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 319.5322265625px;
            }
          }

          @-webkit-keyframes animate-svg-fill-3 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 255, 255);
            }
          }

          @keyframes animate-svg-fill-3 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 255, 255);
            }
          }

          .svg-elem-3 {
            -webkit-animation: animate-svg-stroke-3 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
              animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s
                both;
            animation: animate-svg-stroke-3 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
              animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s
                both;
          }

          @-webkit-keyframes animate-svg-stroke-4 {
            0% {
              stroke-dashoffset: 20.839038848876953px;
              stroke-dasharray: 20.839038848876953px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 20.839038848876953px;
            }
          }

          @keyframes animate-svg-stroke-4 {
            0% {
              stroke-dashoffset: 20.839038848876953px;
              stroke-dasharray: 20.839038848876953px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 20.839038848876953px;
            }
          }

          .svg-elem-4 {
            -webkit-animation: animate-svg-stroke-4 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
              animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s
                both;
            animation: animate-svg-stroke-4 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
              animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s
                both;
          }

          @-webkit-keyframes animate-svg-stroke-5 {
            0% {
              stroke-dashoffset: 187.33932495117188px;
              stroke-dasharray: 187.33932495117188px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 187.33932495117188px;
            }
          }

          @keyframes animate-svg-stroke-5 {
            0% {
              stroke-dashoffset: 187.33932495117188px;
              stroke-dasharray: 187.33932495117188px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 187.33932495117188px;
            }
          }

          @-webkit-keyframes animate-svg-fill-5 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 126, 54);
            }
          }

          @keyframes animate-svg-fill-5 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 126, 54);
            }
          }

          .svg-elem-5 {
            -webkit-animation: animate-svg-stroke-5 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
              animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.2000000000000002s both;
            animation: animate-svg-stroke-5 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
              animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.2000000000000002s both;
          }

          @-webkit-keyframes animate-svg-stroke-6 {
            0% {
              stroke-dashoffset: 187.33934020996094px;
              stroke-dasharray: 187.33934020996094px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 187.33934020996094px;
            }
          }

          @keyframes animate-svg-stroke-6 {
            0% {
              stroke-dashoffset: 187.33934020996094px;
              stroke-dasharray: 187.33934020996094px;
            }

            100% {
              stroke-dashoffset: 0;
              stroke-dasharray: 187.33934020996094px;
            }
          }

          @-webkit-keyframes animate-svg-fill-6 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 126, 54);
            }
          }

          @keyframes animate-svg-fill-6 {
            0% {
              fill: transparent;
            }

            100% {
              fill: rgb(255, 126, 54);
            }
          }

          .svg-elem-6 {
            -webkit-animation: animate-svg-stroke-6 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
              animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s
                both;
            animation: animate-svg-stroke-6 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
              animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s
                both;
          }
        `}
      </style>
    </>
  );
};
export default LogoAnimated;
